version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: linx-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Clint.mariadb
      MYSQL_DATABASE: linx
      MYSQL_USER: linx_user
      MYSQL_PASSWORD: linx_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - linx-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  dashboard:
    build: .
    container_name: linx-dashboard
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - linx-network
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=linx
      - DB_USER=root
      - DB_PASSWORD=Clint.mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/db-test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mariadb_data:
    driver: local
  uploads_data:
    driver: local

networks:
  linx-network:
    driver: bridge